src/surecave/urls.py
from django.contrib import admin
from django.urls import path,include, re_path
from subject1.views import home,property_detail,add_tenant,add_property_lease,dashboard,user_profile,tenant_payment_detail
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', home, name='home'),
    re_path(r'^accounts/', include('allauth.urls')),
    path('accounts/profile/', user_profile, name='account_profile'),
    path('dashboard/',dashboard,name="dashboard"),
    path('property/<str:slug>/', property_detail,name="property-detail"),
    path('property/<str:slug>/add-tenant/', add_tenant,name="add-tenant"),
    path('property/<str:slug>/add-lease/', add_property_lease,name="add-lease"),
    path('property/<str:slug>/payment/detail/', tenant_payment_detail,name="tenant-payment-detail"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/subject1/models.py
from django.db import models
from django.conf import settings
# Create your models here.
User = settings.AUTH_USER_MODEL

class Property(models.Model):
	owner = models.ForeignKey(User,on_delete = models.CASCADE)
	name = models.CharField(max_length = 255)
	image = models.ImageField(blank=True,null=True)
	slug = models.SlugField()
	address = models.TextField()
	tenants = models.ManyToManyField(User,related_name  = "tenants",blank=True,null=True)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)



	def __str__(self):
		return self.name

	def get_property_detail_url(self):

		return f"/property/{self.slug}"
	def get_add_tenant_url(self):

		return f"/property/{self.slug}/add-tenant"

	def get_add_lease_url(self):

		return f"/property/{self.slug}/add-lease"

	def get_tenant_payment_url(self):

		return f"/property/{self.slug}/payment/detail/"



class PropertyLease(models.Model):
	property_to_lease = models.ForeignKey('Property',on_delete=models.CASCADE)
	rent = models.FloatField()
	initial_security_deposit = models.FloatField()
	lease_start_date = models.DateField()
	lease_end_date = models.DateField()
	initial_amount_paid = models.BooleanField(default=False)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

	def __str__(self):
		return str(self.rent)

class UserPayment(models.Model):
	user = models.ForeignKey(User,on_delete = models.CASCADE)
	amount_paid = models.FloatField()
	charge_id = models.CharField(max_length=255)
	property_paid = models.ForeignKey('Property',on_delete=models.CASCADE)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

	def __str__(self):
		return self.user.first_name

src/subject1/forms.py
from django import forms
from .models import PropertyLease
from django.forms import DateInput




class EmailForm(forms.Form):
	email = forms.EmailField()



class PropertyLeaseForm(forms.ModelForm):
	   # teacher_student = forms.CharField(max_length=10,label='phone_number')
	class Meta:
		model = PropertyLease
		fields = ['rent','initial_security_deposit','lease_start_date','lease_end_date']
		widgets = {
			'lease_start_date': DateInput(attrs={'type': 'date'}),
			'lease_end_date': DateInput(attrs={'type': 'date'}),
		}

src/subject1/views.py
from django.shortcuts import render

# Create your views here.
from .models import Property,UserPayment
from .forms import EmailForm,PropertyLeaseForm
from django.contrib.auth import get_user_model
from django.http import HttpResponseRedirect
from django.conf import settings
from django.db.models import Sum,Count
from django.urls import reverse
User = get_user_model()
import stripe
from django.contrib import messages

stripe.api_key = settings.STRIPE_API_KEY



def home(request):
	return HttpResponseRedirect(reverse('account_login'))



def user_profile(request):
	template = "profile.html"
	context = {}
	return render(request,template,context)


def dashboard(request):
	template = "dashboard.html"
	print(request.user.landlord_tenant)
	properties = None
	if request.user.landlord_tenant == "Landlord":
		properties = Property.objects.filter(owner= request.user)

	elif request.user.landlord_tenant == "Tenant":
		try:
			properties = Property.objects.get(tenants=request.user)
		except Property.DoesNotExist:
			properties = None
		

	context = {
		"properties":properties,
		"key" : settings.STRIPE_PUBLISHABLE_KEY,
	}

	return render(request,template,context)



def property_detail(request,slug):

	property_obj = Property.objects.get(slug = slug)
	total_amount_paid = Property.objects.aggregate(Sum('userpayment__amount_paid'))
	print(total_amount_paid)
	number_of_tenants = len(property_obj.tenants.all())
	number_of_payments_made = Property.objects.aggregate(Count('userpayment__amount_paid'))['userpayment__amount_paid__count']


	template = "property-detail.html"
	print("Inside property detail with slug being", slug)

	property_lease = property_obj.propertylease_set.all()
	yearly_earning = 0
	if property_lease:
		property_lease = property_lease[0]
		yearly_earning = property_lease.rent * 12
	amount_to_be_paid = 0.00

	if request.method == "POST":
		print("Post request initiated")

		print("Got a token back from Stripe",request.POST['stripeToken'])
		print("Got the amount",request.POST['amount'])

		charge = stripe.Charge.create(
			amount=request.POST['amount'],
			currency='usd',
			description='A Django charge',
			source=request.POST['stripeToken']
		)
		print("The charge id is",charge["id"])
		print(charge["paid"] == True)
		print(charge["status"] == "succeeded")
		print(charge["amount"])

		if charge["status"] == "succeeded":


			instance,created = UserPayment.objects.get_or_create(user=request.user,
																 amount_paid = charge["amount"],
																 charge_id =charge["id"],
																 property_paid = property_obj)
			if created:
				print("created a new instance")
			else:
				print("did not creat a new one.. something can be wrong thoug..")



	context = {
		"property_obj":property_obj,
		"key" : settings.STRIPE_PUBLISHABLE_KEY,
		"property_lease":property_lease,
		"total_amount_paid":total_amount_paid['userpayment__amount_paid__sum'],
		"yearly_earning":yearly_earning,
		"number_of_tenants":number_of_tenants,
		"number_of_payments_made":number_of_payments_made,
	}

	return render(request,template,context)



def add_tenant(request,slug):
	template = "add_tenant.html"
	property_obj = Property.objects.get(slug=slug)
	form = EmailForm(request.POST or None)
	if form.is_valid():
		email = form.cleaned_data.get("email")
		try:
			user = User.objects.get(email=email)
			property_obj.tenants.add(user)
			property_obj.save()
			print("Form saved")
			messages.success(request, 'Tenant Added Successfully')
			return HttpResponseRedirect(reverse("dashboard"))
		except User.DoesNotExist:
			messages.error(request, 'Tenant Not Found. Try sending an invite again.')

	context = {
		"form":form,
	}
	return render(request,template,context)


def add_property_lease(request,slug):
	template = "add_lease.html"
	property_obj = Property.objects.get(slug=slug)
	form = PropertyLeaseForm(request.POST or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.property_to_lease = property_obj
		instance.save()

		print("--- Lease form saved ---")
		messages.success(request,"Lease was setup successfully")
		return HttpResponseRedirect(reverse("property-detail",kwargs={"slug":property_obj.slug}))


	context = {
		"form":form,
	}

	return render(request,template,context)


def tenant_payment_detail(request,slug):
	template = "tenant_payment_detail.html"
	property_obj = UserPayment.objects.filter(property_paid__slug=slug)
	context = {
		"property_obj" : property_obj,
	}
	return render(request,template,context)

src/subject1/templates/add_lease.html
{% extends 'base.html' %}



{% block content %}

<div class ="row">
	<div class="col-md-5">
<form method="POST"> {% csrf_token %}
	


<label for="id_rent">Rent:</label>
<input class="form-control" type="number" name="rent" step="any" required="" id="id_rent">

<label for="id_initial_security_deposit">Initial security deposit:</label>
<input class="form-control" type="number" name="initial_security_deposit" step="any" required="" id="id_initial_security_deposit" >

<label for="id_lease_start_date">Lease start date:</label>
<input class="form-control" type="date" name="lease_start_date" required="" id="id_lease_start_date">


<label for="id_lease_end_date">Lease end date:</label>
<input class="form-control" type="date" name="lease_end_date" required="" id="id_lease_end_date">


<br/>

<input class="btn btn-sm btn-primary btn-block" type="submit" name="submit">

</form>
</div>
</div>
{% endblock %}

src/subject1/templates/add_tenant.html
{% extends 'base.html' %}



{% block page_heading %}

<h1 class="h3 mb-0 text-gray-800">Add Tenants To Property</h1>

{% endblock %}



{% block content %}
<div class="row">
	<div class="col-md-3">
<form method="POST"> {% csrf_token %}

	<label for="id_email">Email:</label>
	<input type="email" name="email" required="" id="id_email" class="form-control form-control-user">
	<br/>

	
		<input type="Submit" name="Add" class="btn btn-sm btn-primary btn-block">
	

</form>
	</div>



	


</div>

{% endblock %}

src/subject1/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}


<script>
	

	{% block jquery %}


	{% endblock %}
</script>

<h1>Hello World</h1>



{% block content %}



{% if request.user.landlord_tenant == "Landlord" %}
<h3>You have the following properties.</h3>
{% for property in properties %}

<div class="card" style="width: 18rem;">
  <img src="{{ property.image.url }}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{ property.name }}</h5>
    <p class="card-text">{{ property.address }}</p>
    <a href="{{ property.get_property_detail_url}}" class="btn btn-primary">View Details</a>
  </div>
</div>


<!-- <h2>Buy for $5.00</h2>
<form action="" method="post">
  {% csrf_token %}
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="{{ key }}"
          data-description="A Django Charge"
          data-amount="500"
          data-locale="auto"></script>
</form>
 -->

{% endfor %}

{% elif request.user.landlord_tenant == "Tenant" %}

{% if properties %}

<h3>You have been assigned to the following property</h3>

<div class="card" style="width: 18rem;">
  <img src="{{ properties.image.url }}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{ properties.name }}</h5>
    <p class="card-text">{{ properties.address }}</p>
    <a href="{{ properties.get_property_detail_url}}" class="btn btn-primary">View Details</a>
  </div>
</div>



{% else %}

<h3>Please wait for your landlord to assign you to a property. You will be able to see details here once that is done</h3>

{% endif %}

{% endif %}
{% endblock %}

src/subject1/templates/property-detail.html
{% extends 'base.html' %}



{% block page_heading %}

<h1 class="h3 mb-0 text-gray-800">Property Detail</h1>

{% endblock %}









{% block content %}





<!--- LANDLORD SECTION ------>

{% if request.user.landlord_tenant == "Landlord" %}

        <!-- Content Row -->
          <div class="row">

            
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Earnings (Monthly)</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">$
                      {% if  property_lease.rent %}  {{ property_lease.rent }} {% else %} 0 {% endif %}</div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>

           
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Earnings (Annual)</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">$ {{ yearly_earning }} </div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Tenants</div>
                      <div class="row no-gutters align-items-center">
                        <div class="col-auto">
                          <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{ number_of_tenants }}</div>
                        </div>
     
                      </div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>

           
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Total Payments</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">{{ number_of_payments_made }}</div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-comments fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>



      
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Property Details</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Address</th>
                      <th>Amount Paid</th>
                    
                    </tr>
                  </thead>


                  <tbody>
                    <tr>
                      <td>{{ property_obj.name }}</td>
                      <td>{{ property_obj.address }}</td>
                      <td>{{ total_amount_paid }}</td>
                    </tr>
                
                  </tbody>
                </table>
              </div>
            </div>
          </div>


        

          <div class="row">


            
            <div class="col-xl-4 col-lg-5">
              <div class="card shadow mb-4">
                
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Tenants Added To Property</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      
                    </a>
                    
                  </div>
                </div>
               
                <div class="card-body">


                	{% if property_obj.tenants.all  %}

<p>You have following tenants added to your current property</p>
{% for tenant in property_obj.tenants.all %}

<li>{{ tenant }} </li>

{% endfor %}


{% else %}

<p>You do not have any tenant added to the property yet</p>
{% endif %}

<br/>
<a href = "{{ property_obj.get_add_tenant_url }}" > <p>Add More Tenants</p> </a>

            	
                  
               
                </div>
              </div>
            </div>





                        
            <div class="col-xl-4 col-lg-5">
              <div class="card shadow mb-4">
                
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Lease Details</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      
                    </a>
                    
                  </div>
                </div>
               
                <div class="card-body">

                {% if property_lease %}
                <p>Your current lease details are as follows</p>
                <ul>
                	<li>Rent: {{ property_lease.rent }}</li>
                	<li>Security: {{ property_lease.initial_security_deposit }}</li>
                	<li>Start Date: {{ property_lease.lease_start_date }}</li>
                	<li>End Date: {{ property_lease.lease_end_date }}</li>
                </ul>

                {% else %}
                <a href = "{{ property_obj.get_add_lease_url }}" > <p>Set Property Lease</p> </a>

                {% endif %}

				           
                </div>
              </div>
            </div>


                     <div class="col-xl-4 col-lg-5">
              <div class="card shadow mb-4">
                
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Payment Details</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      
                    </a>
                    
                  </div>
                </div>
               
                <div class="card-body">


                <a href = "{{ property_obj.get_tenant_payment_url }}"> <p>See Payment Details</p> </a>

				           
                </div>
              </div>
            </div>
          </div>




<!--- LANDLORD SECTION ENDS HERE  ------>

<!---  TENANT ----- >
{% elif request.user.landlord_tenant == "Tenant" %}




         
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Property Details</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Address</th>
                      <th>Rent</th>
                      <th>Other Payments(Security etc.)</th>
                      <th>Lease Start Date</th>
                      <th>Amount Paid</th>
                     
                    </tr>
                  </thead>

                  <tbody>
                    <tr>
                      <td>{{ property_obj.name }}</td>
                      <td>{{ property_obj.address }}</td>
              <td> {% if  property_lease.rent %} {{ property_lease.rent }} {% else %} NA {% endif %}</td>
              <td>{% if  property_lease.rent %} {{ property_lease.initial_security_deposit }} {% else %} NA {% endif %}</td>
              <td>{% if  property_lease.rent %}  {{ property_lease.lease_start_date }} {% else %} NA {% endif %}</td>
                      <td>{{ total_amount_paid }}</td>
                    </tr>
                
                  </tbody>
                </table>
              </div>
            </div>
          </div>






{% if property_lease %}

<form action="" method="POST" id="payment-form">
<div class ="row">
<div class = "col-md-6">

	{% csrf_token %}
  <div class="form-row">
    <label for="card-element">
      Credit or debit card
    </label>
    <div id="card-element">
      <!-- A Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display form errors. -->
    <div id="card-errors" role="alert"></div>
  </div>

  <div class="form-row">
	<input type="number" name="amount" class="form-control" placeholder="Enter Amount To Pay">
  </div>


  <br/>
<!--   <div class="form-row">
	<button type="button" class="btn btn-primary">Pay Now</button>
  </div> -->
  
  <button>Submit Payment</button>

</div>
</div>
</form>

{% else %}

<h4>You will be able to Pay once your Landlord sets the lease for this property.</h4>

{% endif %}
{% endif %}
<!---  TENANT SECTION ENDS HERE ----- >

{% endblock %}




{% block jquery %}

// Create a Stripe client.
var stripe = Stripe('{{ key }}');


// Create an instance of Elements.
var elements = stripe.elements();

// Custom styling can be passed to options when creating an Element.
// (Note that this demo uses a wider set of styles than the guide below.)
var style = {
  base: {
    color: '#32325d',
    fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
    fontSmoothing: 'antialiased',
    fontSize: '16px',
    '::placeholder': {
      color: '#aab7c4'
    }
  },
  invalid: {
    color: '#fa755a',
    iconColor: '#fa755a'
  }
};

// Create an instance of the card Element.
var card = elements.create('card', {style: style});

// Add an instance of the card Element into the `card-element` <div>.
card.mount('#card-element');

// Handle real-time validation errors from the card Element.
card.addEventListener('change', function(event) {
  var displayError = document.getElementById('card-errors');
  if (event.error) {
    displayError.textContent = event.error.message;
  } else {
    displayError.textContent = '';
  }
});

// Handle form submission.
var form = document.getElementById('payment-form');
form.addEventListener('submit', function(event) {
  event.preventDefault();

  stripe.createToken(card).then(function(result) {
    if (result.error) {
      // Inform the user if there was an error.
      var errorElement = document.getElementById('card-errors');
      errorElement.textContent = result.error.message;
    } else {
      // Send the token to your server.
      stripeTokenHandler(result.token);
    }
  });
});

// Submit the form with the token ID.
function stripeTokenHandler(token) {
  // Insert the token ID into the form so it gets submitted to the server
  var form = document.getElementById('payment-form');
  var hiddenInput = document.createElement('input');
  hiddenInput.setAttribute('type', 'hidden');
  hiddenInput.setAttribute('name', 'stripeToken');
  hiddenInput.setAttribute('value', token.id);
  form.appendChild(hiddenInput);

  // Submit the form
  form.submit();
}
 
{% endblock %}

src/subject1/templates/tenant_payment_detail.html
{% extends 'base.html' %}



{% block page_heading %}

<h1 class="h3 mb-0 text-gray-800">Payment Details</h1>

{% endblock %}





{% block content %}


{% if property_obj %}

   <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Property Details</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Tenant Name</th>
                      <th>Amount Paid</th>
                      <th>Date</th>
                      
                    
                    </tr>
                  </thead>


                  <tbody>

                  	{% for data in property_obj %}
                    <tr>
                      <td>{{ data.user }}</td>
                      <td>{{ data.amount_paid }}</td>
                      <td>{{ data.timestamp }}</td>
     
                    </tr>
                    {% endfor %}
                
                  </tbody>
                </table>
              </div>
            </div>
          </div>
{% else %}

<h4>No payments made yet.</h4>

{% endif %}




{% endblock %}